[tool.poetry]
name = "Ortho4XP"
version = "1.30"
description = "A scenery generator for the X-Plane flight simulator"
authors = ["oscarpilote"]
license = "GPL3"

[tool.poetry.dependencies]
python = "~3.9"
numpy = "1.21.2"
requests = "2.26.0"
Shapely = "1.7.1"
Rtree = "0.9.7"
Pillow = "8.3.2"
pyproj = "3.2.0"

[tool.poetry.dev-dependencies]
flake8 = "3.9.2"
black = "21.9b0"
isort = "5.9.3"
mypy = "0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
src_path = ["src", "Ortho4XP.py"]
multi_line_output="3"
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0
line_length = "79"

[tool.black]
line-length = "79"

[tool.mypy]
files=["src", "Ortho4XP.py"]
warn_return_any = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
